[theme]
base            = "dark"
primaryColor    = "#7c6aff"
backgroundColor = "#080810"
secondaryBackgroundColor = "#0c0c1e"
textColor       = "#f4f4f7"
font            = "sans serif"

[server]
maxUploadSize   = 100
headless        = true

[browser]
gatherUsageStats = false
